Changed majority for async
ccubed/PyMoe pull request #3
Opened 2016-10-18 11:37 UTC by GetRektByMe

hi rory

2016-10-18 13:23 UTC, ccubed requested changes
Also separate out the XML parsing functions in user as async calls with await so other code can run.

2016-10-18 13:23 UTC, ccubed commented on Pymoe/Mal/__init__.py
> +            async with session.get() as r:
This is still blank. Call the actual endpoint.

2016-10-18 13:23 UTC, ccubed commented on Pymoe/Mal/__init__.py
> +                    for item in data.findall('entry'):
Since we're doing async, let's separate the XML parsing into its own functions and await those. this will allow other code to run over top while we're waiting. XML parsing is the most time consuming part of MAL. Not much I can do about the time it takes to parse a 300+ anime user profile or search result.

2016-10-18 13:23 UTC, ccubed commented on Pymoe/Mal/__init__.py
>          anime_data = requests.get(self.apiusers, params={'u': name, 'status': 'all', 'type': 'anime'},
This should be one async call.

2016-10-18 13:23 UTC, ccubed commented on Pymoe/Mal/__init__.py
>          manga_data = requests.get(self.apiusers, params={'u': name, 'status': 'all', 'type': 'manga'},
This should be another async call.

2016-10-18 13:52 UTC, GetRektByMe commented on Pymoe/Mal/__init__.py
> +            async with session.get() as r:
Forgot to add it. I'll fix when home

2016-12-11 14:20 UTC, ccubed commented
Some day.

2016-12-11 14:20 UTC, closed without merging